### ISSUE TITLE
Error 126 loading external dp.kinect2

### ISSUE THREAD

**Issue by noxmox** [diablodale/dp.kinect2#16]
Cant load the latest dpkinect2 external. 

I get: Error 126 loading external dp.kinect2

Seems to be related to fftw3.dll 

Maybe helpful: https://cycling74.com/forums/topic/error-126-loading-external/

Pc, 
win 10 
latest dpkinect2 release

Thanks!

**Comment by noxmox** [comment]
Nevermind, reinstalling the kinect runtime fixed the prob.

**Comment by diablodale** [comment]
closed, no issue.
