### ISSUE TITLE
depthmap = 0 does not allow to output cloud and skeleton anymore

### ISSUE THREAD

**Issue by singularmoments** [diablodale/dp.kinect2#20]
Setup
Shenker (Clevo) W705 laptop with 16 GB RAM, 2 x 500GB SSD drive, Intel i7_4790S cpu
Windows 10 x64 with all current updates

Installed Kinect SDK v2.0_1409
Speech and language pack US ES FR
Installed Max 7.1 x64 and it is registered

Step to reproduce:

With dp.kinect2 v1.0.1, even if you have depthmap = 0,
the cloud(gldepth) and skeleton=1 datas are still outputed.

with dp.kinect2beta1.1.20160307.0
clouds and skeleton are not outputed
but faces is ...

**Comment by diablodale** [comment]
Agreed. I've fixed the beta bug.
The fix is included in the v1.1 beta release beyond 1.1.20160307.0

**Comment by diablodale** [comment]
I've released beta v1.1.20160324.0. It has this bug fix on it. Usual download location https://hidale.com/shop/dp-kinect2/

If you encounter this bug again, I request you reply on this issue so I can investigate it.
