### ISSUE TITLE
Feature request _ Hardware unavailable _ notified

### ISSUE THREAD

**Issue by singularmoments** [diablodale/dp.kinect2#21]
Sometimes, the kinect2 stop to work and an error appear in the max console :
hardware unavailable ...
Perhaps it's due to limited usb3 bandwith or other reason.

But if I close the dp.kinect2 and reopen it, it starts working again.
I was wondering if you could notify with a message through the dump outlet this failure.
This way I could automate the re-open of the dp.kinect2

Thanks

**Comment by diablodale** [comment]
dp.kinect2 already sends a "close 1" message on dumpout when this occurs. You can use this to take action.

Please note: This is a very serious error. It means that the Kinect drivers are reporting that the Kinect sensor is no longer connected properly. This is a symptom of something not working properly with Kinect drivers, graphics drivers, Windows, sensor hardware, or the motherboard.

I recommend you follow step 1 of my setup guide https://github.com/diablodale/dp.kinect2/wiki#setup-guide to verify your hardware compatibility. The link from there will send you to a Microsoft page where you can download and use the  Kinect Configuration Verifier tool to test your hardware

Microsoft has a known issue with their Kinect drivers...it does not properly handly Windows going to sleep or hibernating. Sometime when Windows wakes up, the Kinect drivers do not work correctly. You have to reboot in these cases.
