### ISSUE TITLE
Genreal acces denied

### ISSUE THREAD

**Issue by sebbeJoly** [diablodale/dp.kinect2#24]
I bought a license Dpkinect2 and it is impossible to enregsitrer me. In the Max console, it says " General access denied error. hr = 0x80070005·"

Have you an idea of the problem?

For the moment i run Max 7 Trial...

**Comment by diablodale** [comment]
There are no known issues related to a Max 7 trial. However, it has not been tested.
Please read https://github.com/diablodale/dp.kinect2/issues/1 and provide all the needed information.
