### ISSUE TITLE
smoothing

### ISSUE THREAD

**Issue by dylanmenzies** [diablodale/dp.kinect2#25]
Is there anyway to adjust the smoothing time for positions etc?

**Comment by diablodale** [comment]
The @smoothing attribute can do this. Check out the wiki at
https://github.com/diablodale/dp.kinect2/wiki/Attributes#visual-adjustment
for documentation including deep details with a link to Microsoft.

**Comment by dylanmenzies** [comment]
Thanks for the quick reply.
