### ISSUE TITLE
Skeleton and rgb/depth image combination

### ISSUE THREAD

**Issue by aartcore** [diablodale/dp.kinect2#32]
Hey Diablodale,

I'm working with your dp.kinect2 object. I had some old patches made with jit.openni where i mapped an openGL skeleton (made with jit.gl.sketch) on the rgb en depth image.  Is there already some example patch with the dp.kinect2 of something similar? Would be great!

Thanks,

Aart

**Comment by diablodale** [comment]
The more recent versions of dp.kinect2 have a full helpfile with many tabs of examples. One of them draws a skeleton which could be a source for ideas. You can download the most recent version at hidale.com/shop/dp-kinect2/

In addition, your patch for jit.openni can likely be ported to dp.kinect2 easily. The largest changes are in the pixel width/height of the rgb and depth images. And in the following note from dp.kinect (which also holds true for dp.kinect2)  https://github.com/diablodale/dp.kinect/wiki#compatibility-with-jitopenni
