### ISSUE TITLE
Align color to depth creates a 256 x 424 image

### ISSUE THREAD

**Issue by gavspav** [diablodale/dp.kinect2#4]
I have a Desktop PC running 8.1 64 bit. GTX 860, i5 4690K, 8GB Ram, Z87X D3H
Max 6.1.8 32bit running the month demo

Align color to depth causes the colormap to spit out a 256x424 image (according to jit.fpsgui). Is this correct? I was expecting 512x424

Does the align feature use the sdk to do coordinate mapping? It is a shame that the resolution of the color image needs to be compromised.

**Comment by diablodale** [comment]
In the v1.1 beta of dp.kinect2, I have added the ability to @align=2 depth->color. When using this, the color image will continue to be HD and the other aligned matrices will be extrapolated upwards to have matching resolutions. You can download the beta at the usual location http://hidale.com/shop/dp-kinect2/
