### ISSUE TITLE
Issue registering DPK2 / unzipping reg file

### ISSUE THREAD

**Issue by Unicorpse** [diablodale/dp.kinect2#41]
Hi, I'm trying to register my DP Kinect 2 license (purchased June 2017!) but I can't seem to decompress the reg file to complete registration. I get the error "cannot open file as archive" with 7zip, and I can't redownload the dpreg file as I get "invalid link". 

I have Max 7 (64bit) installed and registered, working on Windows 10.

Thanks!

**Comment by Unicorpse** [comment]
I also can't register a trial license - nothing happens when clicking on "register trial" (including no entries in the Max console)

**Comment by Unicorpse** [comment]
Further update - after resetting Max I can now use the register buttons, and I have the DPREG file, but neither the trial or my licensed DPREG file are working for registration. Here's a screenshot of the console:

![maxdp](https://user-images.githubusercontent.com/35222952/34672002-ae4f60ea-f474-11e7-8e21-98d2e4d5448b.jpg)

**Comment by diablodale** [comment]
I see your order from June 2017. That order is for dp.kinect.
Your screenshot above shows dp.kinect2. The gen-1 and gen-2 Kinect sensors are distinct; as are the software and licenses for each.

You can download the current version of dp.kinect from https://hidale.com/shop/dp-kinect/
I have also re-enabled your license download link. You can try it again now.

With both those downloads, please follow the setup guide here https://github.com/diablodale/dp.kinect/wiki

Does that resolve your issue?

**Comment by Unicorpse** [comment]
Hi Dale, thanks for your answer and good eye! That is really frustrating, I meant way back to purchase DPK2... Hence why I've made that silly mistake. 

Is it at all possible to switch over my license for DPK1 to DPK2? No worries if not.

Thanks for your help!

**Comment by diablodale** [comment]
Yes, I can as you have not yet downloaded the license. 
I can make a new "exchange" order for dp.kinect2.

Can I use the same email address and license info from your original order?

**Comment by Unicorpse** [comment]
That's such a big help, thank you!!!

Yes same info should all apply.

I really appreciate it! Thanks!

**Comment by diablodale** [comment]
On its way via email.
I'll close this issue as resolved. If you have any new related issues with dp.kinect2, you can reopen this issue.
