### ISSUE TITLE
Mac bootcamp windows-can not unregister after deleting windows system and reinstalling

### ISSUE THREAD

**Issue by HanXuJohn12345** [diablodale/dp.kinect2#59]
Hi Dale，

 I have one Macbook and I installed Windows by Bootcamp. 

And then, I reinstalled Windows on the same MacBook, and want to register dp.kinet which result in "Your registration key is already registered on two different computers.

It is only one Mac, which installed Windows 10 by Bootcamp (I have successfully registered your dp.kinect and used it on it). Later I restored windows 10 again by using Bootcamp (now lost access to the windows 10 I registered

Do you not how you fix this problem?

**Comment by diablodale** [comment]
Hello. I do not have enough information to support you. You failed to answer all the questions you were asked.
Please open a new issue and answer all the questions this systems asks you. After I have this information, I can begin the investigation.
