### ISSUE TITLE
Error: loading the ddl for face tracking

### ISSUE THREAD

**Issue by wadox** [diablodale/dp.kinect2#8]
Setup
HP 13-B-110TU laptop, 4 GB RAM, 500GB SSD drive, Intel i5-4210U cpu
Windows 8.1 x64 with all current updates
Installed Kinect 2.0 SDK
Installed Max 6.1.9 x64 and it is registered

Steps
I have downloaded the latest versions from your website: dp.kinect2-v0.35
and face tracking models: dp.kinect2-v0.35-face-models

I saved the unzipped files in the same folder as the patcher.

Result: the max window says:
dp.kinect2: dp.kinect2 requires Kinect20.Face.x64.dll 2.0.1410.19000 or greater + the matching NuiDatabase folder from that release.

Expected: face properties available

**Comment by diablodale** [comment]
Please read issue #1. I need far more information in which to assist you.

**Comment by wadox** [comment]
I have now updated the required above

**Comment by diablodale** [comment]
What step-by-step do you do between "I saved..." and "result". Tell me everything. Pretend I am blind and old and don't know anything.

Meanwhile, please ensure that two files and one subfolder are in the same directory.
dp.kinect2.mxe64
Kinect20.Face.x64.dll
NuiDatabase\

**Comment by wadox** [comment]
Thanks dale I forgot to include the object , I have face properties outputting into the max message window now , to get it to work I included @faces 1 and @faceprop 1

Regards
Dr. Wade Marynowsky 
www.marynowsky.net
0432 940 562

**Comment by diablodale** [comment]
I'm glad is it working for you.
If you begin using the HD face model features (HD 2d points, 3d vertices, SU, etc.), please be aware that the Microsoft recognition technology is very very slow compared to Kinect v1 and needs controlled slow scans of the left, right, top, bottom of the face before it can construct the 3D model.

I'll have the dp.kinect2 documentation updated/completed at https://github.com/diablodale/dp.kinect2/wiki for the final release in a few weeks.

**Comment by diablodale** [comment]
Updated wiki setup section to add clarity
